version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: betteresearch-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=betteresearch
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./app/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - betteresearch-network
    security_opt:
      - no-new-privileges:true
    # Add resource limits for security
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # BetteResearch Electron Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betteresearch-app
    environment:
      - DISPLAY=${DISPLAY}
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=betteresearch
      - PGPASSWORD=postgres
      - PGPORT=5432
      - XAUTHORITY=${XAUTHORITY:-}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/home/appuser/.Xauthority:ro
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: "host"  # Use host networking for X11 forwarding
    security_opt:
      - no-new-privileges:true
    # Add resource limits for security
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

# Persistent volume for PostgreSQL data
volumes:
  postgres-data:

# Network for communication between containers
networks:
  betteresearch-network:
    driver: bridge